# Use official Node image
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy package files first (better caching)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy rest of the code
COPY . .

# Generate Prisma client
RUN npx prisma generate

# 🔥 IMPORTANT for production
RUN npx prisma migrate deploy

# Expose backend port
EXPOSE 5005

# Start server
CMD ["npm", "run", "dev"]